// Auto-generated FT2 GUI layout (schema-based)
#pragma once

#include <stdio.h>
#include "shared/ft2_ui_schema.h"

// Layout name: dx_complete_layout

#ifndef DX_COMPLETE_LAYOUT_PB_BASE
#define DX_COMPLETE_LAYOUT_PB_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_PB_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_CB_BASE
#define DX_COMPLETE_LAYOUT_CB_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_CB_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_RB_BASE
#define DX_COMPLETE_LAYOUT_RB_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_RB_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_SB_BASE
#define DX_COMPLETE_LAYOUT_SB_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_SB_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_TB_BASE
#define DX_COMPLETE_LAYOUT_TB_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TB_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_FB_BASE
#define DX_COMPLETE_LAYOUT_FB_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_FB_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_BMP_BASE
#define DX_COMPLETE_LAYOUT_BMP_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_BMP_COUNT 1

#ifndef DX_COMPLETE_LAYOUT_WAVE_BASE
#define DX_COMPLETE_LAYOUT_WAVE_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_WAVE_COUNT 1

#ifndef DX_COMPLETE_LAYOUT_TF_BUTTON_BASE
#define DX_COMPLETE_LAYOUT_TF_BUTTON_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_BUTTON_COUNT 7

#ifndef DX_COMPLETE_LAYOUT_TF_TOGGLE_BASE
#define DX_COMPLETE_LAYOUT_TF_TOGGLE_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_TOGGLE_COUNT 3

#ifndef DX_COMPLETE_LAYOUT_TF_LABEL_BASE
#define DX_COMPLETE_LAYOUT_TF_LABEL_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_LABEL_COUNT 1

#ifndef DX_COMPLETE_LAYOUT_TF_ROTARY_BASE
#define DX_COMPLETE_LAYOUT_TF_ROTARY_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_ROTARY_COUNT 30

#ifndef DX_COMPLETE_LAYOUT_TF_LINEAR_BASE
#define DX_COMPLETE_LAYOUT_TF_LINEAR_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_LINEAR_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_TF_COMBO_BASE
#define DX_COMPLETE_LAYOUT_TF_COMBO_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_COMBO_COUNT 3

#ifndef DX_COMPLETE_LAYOUT_TF_METER_BASE
#define DX_COMPLETE_LAYOUT_TF_METER_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_METER_COUNT 2

#ifndef DX_COMPLETE_LAYOUT_TF_PARAM_BASE
#define DX_COMPLETE_LAYOUT_TF_PARAM_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_PARAM_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_TF_ENV_BASE
#define DX_COMPLETE_LAYOUT_TF_ENV_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_ENV_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_TF_GROUP_BASE
#define DX_COMPLETE_LAYOUT_TF_GROUP_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_TF_GROUP_COUNT 8

#ifndef DX_COMPLETE_LAYOUT_MIXER_STRIP_BASE
#define DX_COMPLETE_LAYOUT_MIXER_STRIP_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_MIXER_STRIP_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_MIXER_GAIN_BASE
#define DX_COMPLETE_LAYOUT_MIXER_GAIN_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_MIXER_GAIN_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_MIXER_PAN_BASE
#define DX_COMPLETE_LAYOUT_MIXER_PAN_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_MIXER_PAN_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_MIXER_MUTE_BASE
#define DX_COMPLETE_LAYOUT_MIXER_MUTE_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_MIXER_MUTE_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_MIXER_SCOPE_BASE
#define DX_COMPLETE_LAYOUT_MIXER_SCOPE_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_MIXER_SCOPE_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_MIXER_MASTER_BASE
#define DX_COMPLETE_LAYOUT_MIXER_MASTER_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_MIXER_MASTER_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_DSP_WINDOW_BASE
#define DX_COMPLETE_LAYOUT_DSP_WINDOW_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_DSP_WINDOW_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_DSP_SLOT_BASE
#define DX_COMPLETE_LAYOUT_DSP_SLOT_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_DSP_SLOT_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_DSP_MENU_BASE
#define DX_COMPLETE_LAYOUT_DSP_MENU_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_DSP_MENU_COUNT 0

#ifndef DX_COMPLETE_LAYOUT_DSP_PARAM_BASE
#define DX_COMPLETE_LAYOUT_DSP_PARAM_BASE 0
#endif
#define DX_COMPLETE_LAYOUT_DSP_PARAM_COUNT 0

typedef enum {
    DX_COMPLETE_LAYOUT_ACTION_NONE = 0,
} dx_complete_layout_action_id_t;

extern const ft2_ui_layout_desc_t dx_complete_layout_layout;
