// Auto-generated FT2 GUI layout (schema-based)
#pragma once

#include <stdio.h>
#include "shared/ft2_ui_schema.h"

// Layout name: exported_gui

#ifndef EXPORTED_GUI_PB_BASE
#define EXPORTED_GUI_PB_BASE 0
#endif
#define EXPORTED_GUI_PB_COUNT 52

#ifndef EXPORTED_GUI_CB_BASE
#define EXPORTED_GUI_CB_BASE 0
#endif
#define EXPORTED_GUI_CB_COUNT 0

#ifndef EXPORTED_GUI_RB_BASE
#define EXPORTED_GUI_RB_BASE 0
#endif
#define EXPORTED_GUI_RB_COUNT 0

#ifndef EXPORTED_GUI_SB_BASE
#define EXPORTED_GUI_SB_BASE 0
#endif
#define EXPORTED_GUI_SB_COUNT 0

#ifndef EXPORTED_GUI_TB_BASE
#define EXPORTED_GUI_TB_BASE 0
#endif
#define EXPORTED_GUI_TB_COUNT 0

#ifndef EXPORTED_GUI_FB_BASE
#define EXPORTED_GUI_FB_BASE 0
#endif
#define EXPORTED_GUI_FB_COUNT 3

#ifndef EXPORTED_GUI_BMP_BASE
#define EXPORTED_GUI_BMP_BASE 0
#endif
#define EXPORTED_GUI_BMP_COUNT 0

#ifndef EXPORTED_GUI_WAVE_BASE
#define EXPORTED_GUI_WAVE_BASE 0
#endif
#define EXPORTED_GUI_WAVE_COUNT 0

#ifndef EXPORTED_GUI_TF_BUTTON_BASE
#define EXPORTED_GUI_TF_BUTTON_BASE 0
#endif
#define EXPORTED_GUI_TF_BUTTON_COUNT 0

#ifndef EXPORTED_GUI_TF_TOGGLE_BASE
#define EXPORTED_GUI_TF_TOGGLE_BASE 0
#endif
#define EXPORTED_GUI_TF_TOGGLE_COUNT 0

#ifndef EXPORTED_GUI_TF_LABEL_BASE
#define EXPORTED_GUI_TF_LABEL_BASE 0
#endif
#define EXPORTED_GUI_TF_LABEL_COUNT 0

#ifndef EXPORTED_GUI_TF_ROTARY_BASE
#define EXPORTED_GUI_TF_ROTARY_BASE 0
#endif
#define EXPORTED_GUI_TF_ROTARY_COUNT 0

#ifndef EXPORTED_GUI_TF_LINEAR_BASE
#define EXPORTED_GUI_TF_LINEAR_BASE 0
#endif
#define EXPORTED_GUI_TF_LINEAR_COUNT 0

#ifndef EXPORTED_GUI_TF_COMBO_BASE
#define EXPORTED_GUI_TF_COMBO_BASE 0
#endif
#define EXPORTED_GUI_TF_COMBO_COUNT 0

#ifndef EXPORTED_GUI_TF_METER_BASE
#define EXPORTED_GUI_TF_METER_BASE 0
#endif
#define EXPORTED_GUI_TF_METER_COUNT 0

#ifndef EXPORTED_GUI_TF_PARAM_BASE
#define EXPORTED_GUI_TF_PARAM_BASE 0
#endif
#define EXPORTED_GUI_TF_PARAM_COUNT 0

#ifndef EXPORTED_GUI_TF_ENV_BASE
#define EXPORTED_GUI_TF_ENV_BASE 0
#endif
#define EXPORTED_GUI_TF_ENV_COUNT 0

#ifndef EXPORTED_GUI_TF_GROUP_BASE
#define EXPORTED_GUI_TF_GROUP_BASE 0
#endif
#define EXPORTED_GUI_TF_GROUP_COUNT 0

#ifndef EXPORTED_GUI_MIXER_STRIP_BASE
#define EXPORTED_GUI_MIXER_STRIP_BASE 0
#endif
#define EXPORTED_GUI_MIXER_STRIP_COUNT 16

#ifndef EXPORTED_GUI_MIXER_GAIN_BASE
#define EXPORTED_GUI_MIXER_GAIN_BASE 0
#endif
#define EXPORTED_GUI_MIXER_GAIN_COUNT 16

#ifndef EXPORTED_GUI_MIXER_PAN_BASE
#define EXPORTED_GUI_MIXER_PAN_BASE 0
#endif
#define EXPORTED_GUI_MIXER_PAN_COUNT 16

#ifndef EXPORTED_GUI_MIXER_MUTE_BASE
#define EXPORTED_GUI_MIXER_MUTE_BASE 0
#endif
#define EXPORTED_GUI_MIXER_MUTE_COUNT 16

#ifndef EXPORTED_GUI_MIXER_SCOPE_BASE
#define EXPORTED_GUI_MIXER_SCOPE_BASE 0
#endif
#define EXPORTED_GUI_MIXER_SCOPE_COUNT 16

#ifndef EXPORTED_GUI_MIXER_MASTER_BASE
#define EXPORTED_GUI_MIXER_MASTER_BASE 0
#endif
#define EXPORTED_GUI_MIXER_MASTER_COUNT 1

#ifndef EXPORTED_GUI_DSP_WINDOW_BASE
#define EXPORTED_GUI_DSP_WINDOW_BASE 0
#endif
#define EXPORTED_GUI_DSP_WINDOW_COUNT 0

#ifndef EXPORTED_GUI_DSP_SLOT_BASE
#define EXPORTED_GUI_DSP_SLOT_BASE 0
#endif
#define EXPORTED_GUI_DSP_SLOT_COUNT 4

#ifndef EXPORTED_GUI_DSP_MENU_BASE
#define EXPORTED_GUI_DSP_MENU_BASE 0
#endif
#define EXPORTED_GUI_DSP_MENU_COUNT 1

#ifndef EXPORTED_GUI_DSP_PARAM_BASE
#define EXPORTED_GUI_DSP_PARAM_BASE 0
#endif
#define EXPORTED_GUI_DSP_PARAM_COUNT 8

typedef enum {
    EXPORTED_GUI_ACTION_NONE = 0,
    EXPORTED_GUI_ACTION_MIXER_EXIT_4_DOWN = 1,
    EXPORTED_GUI_ACTION_MIXER_EXIT_4_UP = 2,
    EXPORTED_GUI_ACTION_MIX_MASTER_UP_6_DOWN = 3,
    EXPORTED_GUI_ACTION_MIX_MASTER_UP_6_UP = 4,
    EXPORTED_GUI_ACTION_MIX_MASTER_DN_7_DOWN = 5,
    EXPORTED_GUI_ACTION_MIX_MASTER_DN_7_UP = 6,
    EXPORTED_GUI_ACTION_MIX_MASTER_FX_8_DOWN = 7,
    EXPORTED_GUI_ACTION_MIX_MASTER_FX_8_UP = 8,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_0_14_DOWN = 9,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_0_14_UP = 10,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_0_15_DOWN = 11,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_0_15_UP = 12,
    EXPORTED_GUI_ACTION_MIX_FX_0_16_DOWN = 13,
    EXPORTED_GUI_ACTION_MIX_FX_0_16_UP = 14,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_1_22_DOWN = 15,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_1_22_UP = 16,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_1_23_DOWN = 17,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_1_23_UP = 18,
    EXPORTED_GUI_ACTION_MIX_FX_1_24_DOWN = 19,
    EXPORTED_GUI_ACTION_MIX_FX_1_24_UP = 20,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_2_30_DOWN = 21,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_2_30_UP = 22,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_2_31_DOWN = 23,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_2_31_UP = 24,
    EXPORTED_GUI_ACTION_MIX_FX_2_32_DOWN = 25,
    EXPORTED_GUI_ACTION_MIX_FX_2_32_UP = 26,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_3_38_DOWN = 27,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_3_38_UP = 28,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_3_39_DOWN = 29,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_3_39_UP = 30,
    EXPORTED_GUI_ACTION_MIX_FX_3_40_DOWN = 31,
    EXPORTED_GUI_ACTION_MIX_FX_3_40_UP = 32,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_4_46_DOWN = 33,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_4_46_UP = 34,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_4_47_DOWN = 35,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_4_47_UP = 36,
    EXPORTED_GUI_ACTION_MIX_FX_4_48_DOWN = 37,
    EXPORTED_GUI_ACTION_MIX_FX_4_48_UP = 38,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_5_54_DOWN = 39,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_5_54_UP = 40,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_5_55_DOWN = 41,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_5_55_UP = 42,
    EXPORTED_GUI_ACTION_MIX_FX_5_56_DOWN = 43,
    EXPORTED_GUI_ACTION_MIX_FX_5_56_UP = 44,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_6_62_DOWN = 45,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_6_62_UP = 46,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_6_63_DOWN = 47,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_6_63_UP = 48,
    EXPORTED_GUI_ACTION_MIX_FX_6_64_DOWN = 49,
    EXPORTED_GUI_ACTION_MIX_FX_6_64_UP = 50,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_7_70_DOWN = 51,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_7_70_UP = 52,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_7_71_DOWN = 53,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_7_71_UP = 54,
    EXPORTED_GUI_ACTION_MIX_FX_7_72_DOWN = 55,
    EXPORTED_GUI_ACTION_MIX_FX_7_72_UP = 56,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_8_78_DOWN = 57,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_8_78_UP = 58,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_8_79_DOWN = 59,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_8_79_UP = 60,
    EXPORTED_GUI_ACTION_MIX_FX_8_80_DOWN = 61,
    EXPORTED_GUI_ACTION_MIX_FX_8_80_UP = 62,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_9_86_DOWN = 63,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_9_86_UP = 64,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_9_87_DOWN = 65,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_9_87_UP = 66,
    EXPORTED_GUI_ACTION_MIX_FX_9_88_DOWN = 67,
    EXPORTED_GUI_ACTION_MIX_FX_9_88_UP = 68,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_10_94_DOWN = 69,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_10_94_UP = 70,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_10_95_DOWN = 71,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_10_95_UP = 72,
    EXPORTED_GUI_ACTION_MIX_FX_10_96_DOWN = 73,
    EXPORTED_GUI_ACTION_MIX_FX_10_96_UP = 74,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_11_102_DOWN = 75,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_11_102_UP = 76,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_11_103_DOWN = 77,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_11_103_UP = 78,
    EXPORTED_GUI_ACTION_MIX_FX_11_104_DOWN = 79,
    EXPORTED_GUI_ACTION_MIX_FX_11_104_UP = 80,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_12_110_DOWN = 81,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_12_110_UP = 82,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_12_111_DOWN = 83,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_12_111_UP = 84,
    EXPORTED_GUI_ACTION_MIX_FX_12_112_DOWN = 85,
    EXPORTED_GUI_ACTION_MIX_FX_12_112_UP = 86,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_13_118_DOWN = 87,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_13_118_UP = 88,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_13_119_DOWN = 89,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_13_119_UP = 90,
    EXPORTED_GUI_ACTION_MIX_FX_13_120_DOWN = 91,
    EXPORTED_GUI_ACTION_MIX_FX_13_120_UP = 92,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_14_126_DOWN = 93,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_14_126_UP = 94,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_14_127_DOWN = 95,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_14_127_UP = 96,
    EXPORTED_GUI_ACTION_MIX_FX_14_128_DOWN = 97,
    EXPORTED_GUI_ACTION_MIX_FX_14_128_UP = 98,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_15_134_DOWN = 99,
    EXPORTED_GUI_ACTION_MIX_GAIN_UP_15_134_UP = 100,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_15_135_DOWN = 101,
    EXPORTED_GUI_ACTION_MIX_GAIN_DN_15_135_UP = 102,
    EXPORTED_GUI_ACTION_MIX_FX_15_136_DOWN = 103,
    EXPORTED_GUI_ACTION_MIX_FX_15_136_UP = 104,
} exported_gui_action_id_t;

extern const ft2_ui_layout_desc_t exported_gui_layout;
