#pragma once

#include <stdint.h>
#include <stdbool.h>

enum // PUSHBUTTONS
{
	// reserved
	PB_RES_1,
	PB_RES_2,
	PB_RES_3,
	PB_RES_4,
	PB_RES_5,
	PB_RES_6,
	PB_RES_7,
	PB_RES_8,

	// POSITION EDITOR
	PB_POSED_POS_UP,
	PB_POSED_POS_DOWN,
	PB_POSED_INS,
	PB_POSED_PATT_UP,
	PB_POSED_PATT_DOWN,
	PB_POSED_DEL,
	PB_POSED_LEN_UP,
	PB_POSED_LEN_DOWN,
	PB_POSED_REP_UP,
	PB_POSED_REP_DOWN,

	// SONG/PATTERN
	PB_BPM_UP,
	PB_BPM_DOWN,
	PB_SPEED_UP,
	PB_SPEED_DOWN,
	PB_EDITADD_UP,
	PB_EDITADD_DOWN,
	PB_PATT_UP,
	PB_PATT_DOWN,
	PB_PATTLEN_UP,
	PB_PATTLEN_DOWN,
	PB_PATT_EXPAND,
	PB_PATT_SHRINK,

	// LOGO
	PB_LOGO,
	PB_BADGE,
	// MAIN MENU
	PB_ABOUT,
	PB_NIBBLES,
	PB_KILL,
	PB_TRIM,
	PB_EXTEND_VIEW,
	PB_TRANSPOSE,
	PB_INST_ED_EXT,
	PB_SMP_ED_EXT,
	PB_ADV_EDIT,
	PB_ADD_CHANNELS,
	PB_SUB_CHANNELS,
	PB_PLAY_SONG,
	PB_PLAY_PATT,
	PB_STOP,
	PB_RECORD_SONG,
	PB_RECORD_PATT,
	PB_DISK_OP,
	PB_INST_ED,
	PB_SMP_ED,
	PB_CONFIG,
	PB_HELP,
	PB_EXIT_EXT_PATT,

	// INSTRUMENT SWITCHER
	PB_RANGE1,
	PB_RANGE2,
	PB_RANGE3,
	PB_RANGE4,
	PB_RANGE5,
	PB_RANGE6,
	PB_RANGE7,
	PB_RANGE8,
	PB_RANGE9,
	PB_RANGE10,
	PB_RANGE11,
	PB_RANGE12,
	PB_RANGE13,
	PB_RANGE14,
	PB_RANGE15,
	PB_RANGE16,
	PB_SWAP_BANK,
	PB_SAMPLE_LIST_UP,
	PB_SAMPLE_LIST_DOWN,

	// NIBBLES SCREEN
	PB_NIBBLES_PLAY,
	PB_NIBBLES_HELP,
	PB_NIBBLES_HIGHS,
	PB_NIBBLES_EXIT,

	// ADVANCED EDIT
	PB_REMAP_TRACK,
	PB_REMAP_PATTERN,
	PB_REMAP_SONG,
	PB_REMAP_BLOCK,

	// ABOUT SCREEN
	PB_EXIT_ABOUT,

	// HELP SCREEN
	PB_HELP_EXIT,
	PB_HELP_SCROLL_UP,
	PB_HELP_SCROLL_DOWN,

	// PATTERN EDITOR
	PB_CHAN_SCROLL_LEFT,
	PB_CHAN_SCROLL_RIGHT,

	// TRANSPOSE
	PB_TRANSP_CUR_INS_TRK_UP,
	PB_TRANSP_CUR_INS_TRK_DN,
	PB_TRANSP_CUR_INS_TRK_12UP,
	PB_TRANSP_CUR_INS_TRK_12DN,
	PB_TRANSP_ALL_INS_TRK_UP,
	PB_TRANSP_ALL_INS_TRK_DN,
	PB_TRANSP_ALL_INS_TRK_12UP,
	PB_TRANSP_ALL_INS_TRK_12DN,
	PB_TRANSP_CUR_INS_PAT_UP,
	PB_TRANSP_CUR_INS_PAT_DN,
	PB_TRANSP_CUR_INS_PAT_12UP,
	PB_TRANSP_CUR_INS_PAT_12DN,
	PB_TRANSP_ALL_INS_PAT_UP,
	PB_TRANSP_ALL_INS_PAT_DN,
	PB_TRANSP_ALL_INS_PAT_12UP,
	PB_TRANSP_ALL_INS_PAT_12DN,
	PB_TRANSP_CUR_INS_SNG_UP,
	PB_TRANSP_CUR_INS_SNG_DN,
	PB_TRANSP_CUR_INS_SNG_12UP,
	PB_TRANSP_CUR_INS_SNG_12DN,
	PB_TRANSP_ALL_INS_SNG_UP,
	PB_TRANSP_ALL_INS_SNG_DN,
	PB_TRANSP_ALL_INS_SNG_12UP,
	PB_TRANSP_ALL_INS_SNG_12DN,
	PB_TRANSP_CUR_INS_BLK_UP,
	PB_TRANSP_CUR_INS_BLK_DN,
	PB_TRANSP_CUR_INS_BLK_12UP,
	PB_TRANSP_CUR_INS_BLK_12DN,
	PB_TRANSP_ALL_INS_BLK_UP,
	PB_TRANSP_ALL_INS_BLK_DN,
	PB_TRANSP_ALL_INS_BLK_12UP,
	PB_TRANSP_ALL_INS_BLK_12DN,

	// SAMPLE EDITOR
	PB_SAMP_SCROLL_LEFT,
	PB_SAMP_SCROLL_RIGHT,
	PB_SAMP_PNOTE_UP,
	PB_SAMP_PNOTE_DOWN,
	PB_SAMP_STOP,
	PB_SAMP_PWAVE,
	PB_SAMP_PRANGE,
	PB_SAMP_PDISPLAY,
	PB_SAMP_SHOW_RANGE,
	PB_SAMP_RANGE_ALL,
	PB_SAMP_CLR_RANGE,
	PB_SAMP_ZOOM_OUT,
	PB_SAMP_SHOW_ALL,
	PB_SAMP_SAVE_RNG,
	PB_SAMP_CUT,
	PB_SAMP_COPY,
	PB_SAMP_PASTE,
	PB_SAMP_CROP,
	PB_SAMP_VOLUME,
	PB_SAMP_EFFECTS,
	PB_SAMP_EXIT,
	PB_SAMP_CLEAR,
	PB_SAMP_MIN,
	PB_SAMP_REPEAT_UP,
	PB_SAMP_REPEAT_DOWN,
	PB_SAMP_REPLEN_UP,
	PB_SAMP_REPLEN_DOWN,

	// SAMPLE EDITOR EFFECTS SCREEN
	PB_SAMPFX_CYCLES_UP,
	PB_SAMPFX_CYCLES_DOWN,
	PB_SAMPFX_TRIANGLE,
	PB_SAMPFX_SAW,
	PB_SAMPFX_SINE,
	PB_SAMPFX_SQUARE,
	PB_SAMPFX_RESO_UP,
	PB_SAMPFX_RESO_DOWN,
	PB_SAMPFX_LOWPASS,
	PB_SAMPFX_HIGHPASS,
	PB_SAMPFX_SUB_BASS,
	PB_SAMPFX_SUB_TREBLE,
	PB_SAMPFX_ADD_BASS,
	PB_SAMPFX_ADD_TREBLE,
	PB_SAMPFX_SET_AMP,
	PB_SAMPFX_UNDO,
	PB_SAMPFX_XFADE,
	PB_SAMPFX_BACK,

	// SAMPLE EDITOR EXTENSION
	PB_SAMP_EXT_CLEAR_COPYBUF,
	PB_SAMP_EXT_CONV,
	PB_SAMP_EXT_ECHO,
	PB_SAMP_EXT_BACKWARDS,
	PB_SAMP_EXT_CONV_W,
	PB_SAMP_EXT_MORPH,
	PB_SAMP_EXT_COPY_INS,
	PB_SAMP_EXT_COPY_SMP,
	PB_SAMP_EXT_XCHG_INS,
	PB_SAMP_EXT_XCHG_SMP,
	PB_SAMP_EXT_RESAMPLE,
	PB_SAMP_EXT_MIX_SAMPLE,

	// INSTRUMENT EDITOR
	PB_INST_VDEF1,
	PB_INST_VDEF2,
	PB_INST_VDEF3,
	PB_INST_VDEF4,
	PB_INST_VDEF5,
	PB_INST_VDEF6,
	PB_INST_PDEF1,
	PB_INST_PDEF2,
	PB_INST_PDEF3,
	PB_INST_PDEF4,
	PB_INST_PDEF5,
	PB_INST_PDEF6,
	PB_INST_VP_ADD,
	PB_INST_VP_DEL,
	PB_INST_VS_UP,
	PB_INST_VS_DOWN,
	PB_INST_VREPS_UP,
	PB_INST_VREPS_DOWN,
	PB_INST_VREPE_UP,
	PB_INST_VREPE_DOWN,
	PB_INST_PP_ADD,
	PB_INST_PP_DEL,
	PB_INST_PS_UP,
	PB_INST_PS_DOWN,
	PB_INST_PREPS_UP,
	PB_INST_PREPS_DOWN,
	PB_INST_PREPE_UP,
	PB_INST_PREPE_DOWN,
	PB_INST_VOL_DOWN,
	PB_INST_VOL_UP,
	PB_INST_PAN_DOWN,
	PB_INST_PAN_UP,
	PB_INST_FTUNE_DOWN,
	PB_INST_FTUNE_UP,
	PB_INST_FADEOUT_DOWN,
	PB_INST_FADEOUT_UP,
	PB_INST_VIBSPEED_DOWN,
	PB_INST_VIBSPEED_UP,
	PB_INST_VIBDEPTH_DOWN,
	PB_INST_VIBDEPTH_UP,
	PB_INST_VIBSWEEP_DOWN,
	PB_INST_VIBSWEEP_UP,
	PB_INST_V2,
	PB_INST_OSTIRUS,
	PB_INST_TF4,
	PB_INST_DEXED,
	PB_INST_OCT_UP,
	PB_INST_HALFTONE_UP,
	PB_INST_OCT_DOWN,
	PB_INST_HALFTONE_DOWN,

	// INSTRUMENT EDITOR EXTENSION
	PB_INST_EXT_MIDI_CH_DOWN,
	PB_INST_EXT_MIDI_CH_UP,
	PB_INST_EXT_MIDI_PRG_DOWN,
	PB_INST_EXT_MIDI_PRG_UP,
	PB_INST_EXT_MIDI_BEND_DOWN,
	PB_INST_EXT_MIDI_BEND_UP,

	// TRIM SCREEN
	PB_TRIM_CALC,
	PB_TRIM_TRIM,

	// CONFIG LEFT PANEL
	PB_CONFIG_RESET,
	PB_CONFIG_LOAD,
	PB_CONFIG_SAVE,
	PB_CONFIG_EXIT,

	// CONFIG AUDIO
	PB_CONFIG_AUDIO_RESCAN,
	PB_CONFIG_AUDIO_OUTPUT_DOWN,
	PB_CONFIG_AUDIO_OUTPUT_UP,
	PB_CONFIG_AUDIO_INPUT_DOWN,
	PB_CONFIG_AUDIO_INPUT_UP,
	PB_CONFIG_AMP_DOWN,
	PB_CONFIG_AMP_UP,
	PB_CONFIG_MASTVOL_DOWN,
	PB_CONFIG_MASTVOL_UP,

	// CONFIG LAYOUT
	PB_CONFIG_PAL_R_DOWN,
	PB_CONFIG_PAL_R_UP,
	PB_CONFIG_PAL_G_DOWN,
	PB_CONFIG_PAL_G_UP,
	PB_CONFIG_PAL_B_DOWN,
	PB_CONFIG_PAL_B_UP,
	PB_CONFIG_PAL_CONT_DOWN,
	PB_CONFIG_PAL_CONT_UP,

	// CONFIG MISCELLANEOUS
	PB_CONFIG_QUANTIZE_UP,
	PB_CONFIG_QUANTIZE_DOWN,
	PB_CONFIG_MIDICHN_UP,
	PB_CONFIG_MIDICHN_DOWN,
	PB_CONFIG_MIDITRANS_UP,
	PB_CONFIG_MIDITRANS_DOWN,
	PB_CONFIG_MIDISENS_DOWN,
	PB_CONFIG_MIDISENS_UP,

#ifdef HAS_MIDI
	// CONFIG MIDI
	PB_CONFIG_MIDI_INPUT_DOWN,
	PB_CONFIG_MIDI_INPUT_UP,
#endif

	// DISK OP.
	PB_DISKOP_SAVE,
	PB_DISKOP_DELETE,
	PB_DISKOP_RENAME,
	PB_DISKOP_MAKEDIR,
	PB_DISKOP_REFRESH,
	PB_DISKOP_SET_PATH,
	PB_DISKOP_SHOW_ALL,
	PB_DISKOP_EXIT,
	PB_DISKOP_ROOT,
	PB_DISKOP_PARENT,
#ifdef _WIN32
	PB_DISKOP_DRIVE1,
	PB_DISKOP_DRIVE2,
	PB_DISKOP_DRIVE3,
	PB_DISKOP_DRIVE4,
	PB_DISKOP_DRIVE5,
	PB_DISKOP_DRIVE6,
	PB_DISKOP_DRIVE7,
	PB_DISKOP_DRIVE8,
#endif
	PB_DISKOP_LIST_UP,
	PB_DISKOP_LIST_DOWN,

	// WAV RENDERER
	PB_WAV_RENDER,
	PB_WAV_EXIT,
	PB_WAV_FREQ_UP,
	PB_WAV_FREQ_DOWN,
	PB_WAV_AMP_UP,
	PB_WAV_AMP_DOWN,
	PB_WAV_START_UP,
	PB_WAV_START_DOWN,
	PB_WAV_END_UP,
	PB_WAV_END_DOWN,
	PB_WAV_SETTINGS,

	// please keep these at the end
	PB_MIX_GAIN_UP_0, PB_MIX_GAIN_UP_1, PB_MIX_GAIN_UP_2, PB_MIX_GAIN_UP_3,
	PB_MIX_GAIN_UP_4, PB_MIX_GAIN_UP_5, PB_MIX_GAIN_UP_6, PB_MIX_GAIN_UP_7,
	PB_MIX_GAIN_UP_8, PB_MIX_GAIN_UP_9, PB_MIX_GAIN_UP_10, PB_MIX_GAIN_UP_11,
	PB_MIX_GAIN_UP_12, PB_MIX_GAIN_UP_13, PB_MIX_GAIN_UP_14, PB_MIX_GAIN_UP_15,
	PB_MIX_GAIN_UP_16, PB_MIX_GAIN_UP_17, PB_MIX_GAIN_UP_18, PB_MIX_GAIN_UP_19,
	PB_MIX_GAIN_UP_20, PB_MIX_GAIN_UP_21, PB_MIX_GAIN_UP_22, PB_MIX_GAIN_UP_23,
	PB_MIX_GAIN_UP_24, PB_MIX_GAIN_UP_25, PB_MIX_GAIN_UP_26, PB_MIX_GAIN_UP_27,
	PB_MIX_GAIN_UP_28, PB_MIX_GAIN_UP_29, PB_MIX_GAIN_UP_30, PB_MIX_GAIN_UP_31,

	PB_MIX_GAIN_DN_0, PB_MIX_GAIN_DN_1, PB_MIX_GAIN_DN_2, PB_MIX_GAIN_DN_3,
	PB_MIX_GAIN_DN_4, PB_MIX_GAIN_DN_5, PB_MIX_GAIN_DN_6, PB_MIX_GAIN_DN_7,
	PB_MIX_GAIN_DN_8, PB_MIX_GAIN_DN_9, PB_MIX_GAIN_DN_10, PB_MIX_GAIN_DN_11,
	PB_MIX_GAIN_DN_12, PB_MIX_GAIN_DN_13, PB_MIX_GAIN_DN_14, PB_MIX_GAIN_DN_15,
	PB_MIX_GAIN_DN_16, PB_MIX_GAIN_DN_17, PB_MIX_GAIN_DN_18, PB_MIX_GAIN_DN_19,
	PB_MIX_GAIN_DN_20, PB_MIX_GAIN_DN_21, PB_MIX_GAIN_DN_22, PB_MIX_GAIN_DN_23,
	PB_MIX_GAIN_DN_24, PB_MIX_GAIN_DN_25, PB_MIX_GAIN_DN_26, PB_MIX_GAIN_DN_27,
	PB_MIX_GAIN_DN_28, PB_MIX_GAIN_DN_29, PB_MIX_GAIN_DN_30, PB_MIX_GAIN_DN_31,

	PB_MIX_DSP_0, PB_MIX_DSP_1, PB_MIX_DSP_2, PB_MIX_DSP_3,
	PB_MIX_DSP_4, PB_MIX_DSP_5, PB_MIX_DSP_6, PB_MIX_DSP_7,
	PB_MIX_DSP_8, PB_MIX_DSP_9, PB_MIX_DSP_10, PB_MIX_DSP_11,
	PB_MIX_DSP_12, PB_MIX_DSP_13, PB_MIX_DSP_14, PB_MIX_DSP_15,
	PB_MIX_DSP_16, PB_MIX_DSP_17, PB_MIX_DSP_18, PB_MIX_DSP_19,
	PB_MIX_DSP_20, PB_MIX_DSP_21, PB_MIX_DSP_22, PB_MIX_DSP_23,
	PB_MIX_DSP_24, PB_MIX_DSP_25, PB_MIX_DSP_26, PB_MIX_DSP_27,
	PB_MIX_DSP_28, PB_MIX_DSP_29, PB_MIX_DSP_30, PB_MIX_DSP_31,

	PB_MIX_MUTE_0, PB_MIX_MUTE_1, PB_MIX_MUTE_2, PB_MIX_MUTE_3,
	PB_MIX_MUTE_4, PB_MIX_MUTE_5, PB_MIX_MUTE_6, PB_MIX_MUTE_7,
	PB_MIX_MUTE_8, PB_MIX_MUTE_9, PB_MIX_MUTE_10, PB_MIX_MUTE_11,
	PB_MIX_MUTE_12, PB_MIX_MUTE_13, PB_MIX_MUTE_14, PB_MIX_MUTE_15,
	PB_MIX_MUTE_16, PB_MIX_MUTE_17, PB_MIX_MUTE_18, PB_MIX_MUTE_19,
	PB_MIX_MUTE_20, PB_MIX_MUTE_21, PB_MIX_MUTE_22, PB_MIX_MUTE_23,
	PB_MIX_MUTE_24, PB_MIX_MUTE_25, PB_MIX_MUTE_26, PB_MIX_MUTE_27,
	PB_MIX_MUTE_28, PB_MIX_MUTE_29, PB_MIX_MUTE_30, PB_MIX_MUTE_31,

	// Synth Editor: Global controls (moved)
	PB_SYNTH_POLY_UP,
	PB_SYNTH_POLY_DOWN,
	PB_SYNTH_PITCH_UP,
	PB_SYNTH_PITCH_DOWN,
	PB_SYNTH_PATCH_UP,
	PB_SYNTH_PATCH_DOWN,

	// Synth Editor: Generator controls
	PB_SYNTH_GEN_VOLUME_UP,
	PB_SYNTH_GEN_VOLUME_DOWN,
	PB_SYNTH_GEN_PANNING_UP,
	PB_SYNTH_GEN_PANNING_DOWN,
	PB_SYNTH_GEN_SPREAD_UP,
	PB_SYNTH_GEN_SPREAD_DOWN,
	PB_SYNTH_GEN_BANDWIDTH_UP,
	PB_SYNTH_GEN_BANDWIDTH_DOWN,
	PB_SYNTH_GEN_DAMP_UP,
	PB_SYNTH_GEN_DAMP_DOWN,
	PB_SYNTH_GEN_HARMONICS_UP,
	PB_SYNTH_GEN_HARMONICS_DOWN,
	PB_SYNTH_GEN_DRIVE_UP,
	PB_SYNTH_GEN_DRIVE_DOWN,
	PB_SYNTH_GEN_SCALE_UP,
	PB_SYNTH_GEN_SCALE_DOWN,
	PB_SYNTH_GEN_MODULATION_UP,
	PB_SYNTH_GEN_MODULATION_DOWN,
	PB_SYNTH_GEN_NOISE_UP,
	PB_SYNTH_GEN_NOISE_DOWN,
	PB_SYNTH_GEN_NOISE_FREQ_UP,
	PB_SYNTH_GEN_NOISE_FREQ_DOWN,
	PB_SYNTH_GEN_NOISE_BW_UP,
	PB_SYNTH_GEN_NOISE_BW_DOWN,

	// Synth Editor: Filter controls
	PB_SYNTH_FILTER_LP_FREQ_UP,
	PB_SYNTH_FILTER_LP_FREQ_DOWN,
	PB_SYNTH_FILTER_LP_RES_UP,
	PB_SYNTH_FILTER_LP_RES_DOWN,
	PB_SYNTH_FILTER_HPF_FREQ_UP,
	PB_SYNTH_FILTER_HPF_FREQ_DOWN,
	PB_SYNTH_FILTER_HPF_RES_UP,
	PB_SYNTH_FILTER_HPF_RES_DOWN,
	PB_SYNTH_FILTER_BPF_FREQ_UP,
	PB_SYNTH_FILTER_BPF_FREQ_DOWN,
	PB_SYNTH_FILTER_BPF_RES_UP,
	PB_SYNTH_FILTER_BPF_RES_DOWN,
	PB_SYNTH_FILTER_NT_FREQ_UP,
	PB_SYNTH_FILTER_NT_FREQ_DOWN,
	PB_SYNTH_FILTER_NT_RES_UP,
	PB_SYNTH_FILTER_NT_RES_DOWN,

	// Synth Editor: LFO controls
	PB_SYNTH_LFO1_RATE_UP,
	PB_SYNTH_LFO1_RATE_DOWN,
	PB_SYNTH_LFO1_DEPTH_UP,
	PB_SYNTH_LFO1_DEPTH_DOWN,
	PB_SYNTH_LFO2_RATE_UP,
	PB_SYNTH_LFO2_RATE_DOWN,
	PB_SYNTH_LFO2_DEPTH_UP,
	PB_SYNTH_LFO2_DEPTH_DOWN,

	// Synth Editor: ADSR controls
	PB_SYNTH_ADSR1_A_UP,
	PB_SYNTH_ADSR1_A_DOWN,
	PB_SYNTH_ADSR1_D_UP,
	PB_SYNTH_ADSR1_D_DOWN,
	PB_SYNTH_ADSR1_S_UP,
	PB_SYNTH_ADSR1_S_DOWN,
	PB_SYNTH_ADSR1_R_UP,
	PB_SYNTH_ADSR1_R_DOWN,
	PB_SYNTH_ADSR2_A_UP,
	PB_SYNTH_ADSR2_A_DOWN,
	PB_SYNTH_ADSR2_D_UP,
	PB_SYNTH_ADSR2_D_DOWN,
	PB_SYNTH_ADSR2_S_UP,
	PB_SYNTH_ADSR2_S_DOWN,
	PB_SYNTH_ADSR2_R_UP,
	PB_SYNTH_ADSR2_R_DOWN,

	// Synth Editor: FX controls (Flanger)
	PB_SYNTH_FX_FLANGER_LFO_UP,
	PB_SYNTH_FX_FLANGER_LFO_DOWN,
	PB_SYNTH_FX_FLANGER_FREQ_UP,
	PB_SYNTH_FX_FLANGER_FREQ_DOWN,
	PB_SYNTH_FX_FLANGER_AMP_UP,
	PB_SYNTH_FX_FLANGER_AMP_DOWN,
	PB_SYNTH_FX_FLANGER_WET_UP,
	PB_SYNTH_FX_FLANGER_WET_DOWN,

	// Synth Editor: FX controls (Reverb)
	PB_SYNTH_FX_REVERB_ROOMSZ_UP,
	PB_SYNTH_FX_REVERB_ROOMSZ_DOWN,
	PB_SYNTH_FX_REVERB_DAMP_UP,
	PB_SYNTH_FX_REVERB_DAMP_DOWN,
	PB_SYNTH_FX_REVERB_WET_UP,
	PB_SYNTH_FX_REVERB_WET_DOWN,
	PB_SYNTH_FX_REVERB_WIDTH_UP,
	PB_SYNTH_FX_REVERB_WIDTH_DOWN,

	// Synth Editor: FX controls (Delay)
	PB_SYNTH_FX_DELAY_LEFT_UP,
	PB_SYNTH_FX_DELAY_LEFT_DOWN,
	PB_SYNTH_FX_DELAY_RIGHT_UP,
	PB_SYNTH_FX_DELAY_RIGHT_DOWN,
	PB_SYNTH_FX_DELAY_DECAY_UP,
	PB_SYNTH_FX_DELAY_DECAY_DOWN,

	// Synth Editor: FX controls (EQ)
	PB_SYNTH_FX_EQ_BASS_UP,
	PB_SYNTH_FX_EQ_BASS_DOWN,
	PB_SYNTH_FX_EQ_MID_UP,
	PB_SYNTH_FX_EQ_MID_DOWN,
	PB_SYNTH_FX_EQ_TREBLE_UP,
	PB_SYNTH_FX_EQ_TREBLE_DOWN,

	// Synth Editor: FX controls (Chorus)
	PB_SYNTH_FX_CHORUS_FREQ_UP,
	PB_SYNTH_FX_CHORUS_FREQ_DOWN,
	PB_SYNTH_FX_CHORUS_DEPTH_UP,
	PB_SYNTH_FX_CHORUS_DEPTH_DOWN,
	PB_SYNTH_FX_CHORUS_GAIN_UP,
	PB_SYNTH_FX_CHORUS_GAIN_DOWN,

	// Synth Editor: FX controls (Formant)
	PB_SYNTH_FX_FORMANT_WET_UP,
	PB_SYNTH_FX_FORMANT_WET_DOWN,
	PB_SYNTH_FX_FORMANT_A_UP,
	PB_SYNTH_FX_FORMANT_A_DOWN,
	PB_SYNTH_FX_FORMANT_E_UP,
	PB_SYNTH_FX_FORMANT_E_DOWN,
	PB_SYNTH_FX_FORMANT_I_UP,
	PB_SYNTH_FX_FORMANT_I_DOWN,
	PB_SYNTH_FX_FORMANT_O_UP,
	PB_SYNTH_FX_FORMANT_O_DOWN,
	PB_SYNTH_FX_FORMANT_U_UP,
	PB_SYNTH_FX_FORMANT_U_DOWN,

	// Synth Editor: FX controls (Distortion)
	PB_SYNTH_FX_DISTORTION_AMOUNT_UP,
	PB_SYNTH_FX_DISTORTION_AMOUNT_DOWN,

	// Synth Editor: Mod Matrix controls (6 IDs per slot)
	PB_SYNTH_MM_SRC1_UP,	PB_SYNTH_MM_SRC1_DOWN,
	PB_SYNTH_MM_DST1_UP,	PB_SYNTH_MM_DST1_DOWN,
	PB_SYNTH_MM_AMT1_UP,	PB_SYNTH_MM_AMT1_DOWN,
	PB_SYNTH_MM_SRC2_UP,	PB_SYNTH_MM_SRC2_DOWN,
	PB_SYNTH_MM_DST2_UP,	PB_SYNTH_MM_DST2_DOWN,
	PB_SYNTH_MM_AMT2_UP,	PB_SYNTH_MM_AMT2_DOWN,
	PB_SYNTH_MM_SRC3_UP,	PB_SYNTH_MM_SRC3_DOWN,
	PB_SYNTH_MM_DST3_UP,	PB_SYNTH_MM_DST3_DOWN,
	PB_SYNTH_MM_AMT3_UP,	PB_SYNTH_MM_AMT3_DOWN,
	PB_SYNTH_MM_SRC4_UP,	PB_SYNTH_MM_SRC4_DOWN,
	PB_SYNTH_MM_DST4_UP,	PB_SYNTH_MM_DST4_DOWN,
	PB_SYNTH_MM_AMT4_UP,	PB_SYNTH_MM_AMT4_DOWN,
	PB_SYNTH_MM_SRC5_UP,	PB_SYNTH_MM_SRC5_DOWN,
	PB_SYNTH_MM_DST5_UP,	PB_SYNTH_MM_DST5_DOWN,
	PB_SYNTH_MM_AMT5_UP,	PB_SYNTH_MM_AMT5_DOWN,
	PB_SYNTH_MM_SRC6_UP,	PB_SYNTH_MM_SRC6_DOWN,
	PB_SYNTH_MM_DST6_UP,	PB_SYNTH_MM_DST6_DOWN,
	PB_SYNTH_MM_AMT6_UP,	PB_SYNTH_MM_AMT6_DOWN,
	PB_SYNTH_MM_SRC7_UP,	PB_SYNTH_MM_SRC7_DOWN,
	PB_SYNTH_MM_DST7_UP,	PB_SYNTH_MM_DST7_DOWN,
	PB_SYNTH_MM_AMT7_UP,	PB_SYNTH_MM_AMT7_DOWN,
	PB_SYNTH_MM_SRC8_UP,	PB_SYNTH_MM_SRC8_DOWN,
	PB_SYNTH_MM_DST8_UP,	PB_SYNTH_MM_DST8_DOWN,
	PB_SYNTH_MM_AMT8_UP,	PB_SYNTH_MM_AMT8_DOWN,

	// Synth Editor: FX Stack controls (2 IDs per slot)
	PB_SYNTH_FX_STACK1_UP,	PB_SYNTH_FX_STACK1_DOWN,
	PB_SYNTH_FX_STACK2_UP,	PB_SYNTH_FX_STACK2_DOWN,
	PB_SYNTH_FX_STACK3_UP,	PB_SYNTH_FX_STACK3_DOWN,
	PB_SYNTH_FX_STACK4_UP,	PB_SYNTH_FX_STACK4_DOWN,
	PB_SYNTH_FX_STACK5_UP,	PB_SYNTH_FX_STACK5_DOWN,
	PB_SYNTH_FX_STACK6_UP,	PB_SYNTH_FX_STACK6_DOWN,
	PB_SYNTH_FX_STACK7_UP,	PB_SYNTH_FX_STACK7_DOWN,
	PB_SYNTH_FX_STACK8_UP,	PB_SYNTH_FX_STACK8_DOWN,
	PB_SYNTH_PAGE_TOGGLE,
	PB_SYNTH_EXIT,

	// Render Settings modal (configured dynamically)
	PB_RENDER_SETTINGS_OK,
	PB_RENDER_SETTINGS_CANCEL,
	PB_RENDER_SETTINGS_SLOT_DOWN,
	PB_RENDER_SETTINGS_SLOT_UP,
	PB_RENDER_SETTINGS_RATE_DOWN,
	PB_RENDER_SETTINGS_RATE_UP,

	// Appended (not interspersed with existing IDs - see note above PB_TF_BASE).
	// Fields are set dynamically in ft2_inst_ed.c rather than via the static
	// pushButtons[] literal, since that literal's positional coverage ends at the
	// WAV RENDERER section.

	NUM_PUSHBUTTONS
};

#define PB_RENDER_SETTINGS_FIRST PB_RENDER_SETTINGS_OK
#define PB_RENDER_SETTINGS_LAST  (PB_RENDER_SETTINGS_RATE_UP + 1)

// Append-only ID ranges for designer-driven layouts (do not reorder existing IDs).
#define PB_TF_BASE NUM_PUSHBUTTONS
#define PB_TF_COUNT 0
#define PB_DX_BASE (PB_TF_BASE + PB_TF_COUNT)
#define PB_DX_COUNT 0
#define PB_MIXER_BASE (PB_DX_BASE + PB_DX_COUNT)
#define PB_MIXER_COUNT 0
#define PB_DSP_BASE (PB_MIXER_BASE + PB_MIXER_COUNT)
#define PB_DSP_COUNT 0
#define PB_MACRO_MAP_BASE (PB_DSP_BASE + PB_DSP_COUNT)
#define PB_MACRO_MAP_COUNT 0

enum
{
	PUSHBUTTON_UNPRESSED = 0,
	PUSHBUTTON_PRESSED   = 1
};

// amount of frames to wait
#define BUTTON_DOWN_DELAY 25

// special characters (used for buttons)

#define ARROW_UP_GFX_CHAR 0x01
#define ARROW_UP_STRING "\x01"

#define ARROW_DOWN_GFX_CHAR 0x02
#define ARROW_DOWN_STRING "\x02"

#define ARROW_LEFT_GFX_CHAR 0x03
#define ARROW_LEFT_STRING "\x03"

#define ARROW_RIGHT_GFX_CHAR 0x04
#define ARROW_RIGHT_STRING "\x04"

#define SMALL_1_GFX_CHAR 0x05
#define SMALL_1_STRING "\x05"

#define SMALL_2_GFX_CHAR 0x06
#define SMALL_2_STRING "\x06"

#define SMALL_3_GFX_CHAR 0x07
#define SMALL_3_STRING "\x07"

#define SMALL_4_GFX_CHAR 0x08
#define SMALL_4_STRING "\x08"

#define SMALL_5_GFX_CHAR 0x09
#define SMALL_5_STRING "\x09"

#define SMALL_6_GFX_CHAR 0x0A
#define SMALL_6_STRING "\x0A"

#define DISKOP_PARENT_GFX_CHAR 0x0B
#define DISKOP_PARENT_STRING "\x0B"

#define FT2_PB_MIX_MUTE_LAST PB_MIX_MUTE_31

typedef struct pushButton_t // DO NOT TOUCH!
{
	uint16_t x, y, w, h;
	uint8_t preDelay, delayFrames;
	char *caption, *caption2;
	void (*callbackFuncOnDown)(void);
	void (*callbackFuncOnUp)(void);
	uint8_t state;
	bool bitmapFlag, visible;
	const uint8_t *bitmapUnpressed;
	const uint8_t *bitmapPressed;
} pushButton_t;

void drawPushButton(uint16_t pushButtonID);
void showPushButton(uint16_t pushButtonID);
void hidePushButton(uint16_t pushButtonID);
void handlePushButtonsWhileMouseDown(void);
bool testPushButtonMouseDown(void);
int16_t testPushButtonMouseRelease(bool runCallback);
