// Auto-generated FT2 GUI layout (schema-based)
#pragma once

#include <stdio.h>
#include "shared/ft2_ui_schema.h"

// Layout name: ft2_mixer_layout

#ifndef FT2_MIXER_LAYOUT_PB_BASE
#define FT2_MIXER_LAYOUT_PB_BASE 0
#endif
#define FT2_MIXER_LAYOUT_PB_COUNT 52

#ifndef FT2_MIXER_LAYOUT_CB_BASE
#define FT2_MIXER_LAYOUT_CB_BASE 0
#endif
#define FT2_MIXER_LAYOUT_CB_COUNT 0

#ifndef FT2_MIXER_LAYOUT_RB_BASE
#define FT2_MIXER_LAYOUT_RB_BASE 0
#endif
#define FT2_MIXER_LAYOUT_RB_COUNT 0

#ifndef FT2_MIXER_LAYOUT_SB_BASE
#define FT2_MIXER_LAYOUT_SB_BASE 0
#endif
#define FT2_MIXER_LAYOUT_SB_COUNT 1

#ifndef FT2_MIXER_LAYOUT_TB_BASE
#define FT2_MIXER_LAYOUT_TB_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TB_COUNT 0

#ifndef FT2_MIXER_LAYOUT_FB_BASE
#define FT2_MIXER_LAYOUT_FB_BASE 0
#endif
#define FT2_MIXER_LAYOUT_FB_COUNT 0

#ifndef FT2_MIXER_LAYOUT_BMP_BASE
#define FT2_MIXER_LAYOUT_BMP_BASE 0
#endif
#define FT2_MIXER_LAYOUT_BMP_COUNT 1

#ifndef FT2_MIXER_LAYOUT_WAVE_BASE
#define FT2_MIXER_LAYOUT_WAVE_BASE 0
#endif
#define FT2_MIXER_LAYOUT_WAVE_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_BUTTON_BASE
#define FT2_MIXER_LAYOUT_TF_BUTTON_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_BUTTON_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_TOGGLE_BASE
#define FT2_MIXER_LAYOUT_TF_TOGGLE_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_TOGGLE_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_LABEL_BASE
#define FT2_MIXER_LAYOUT_TF_LABEL_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_LABEL_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_ROTARY_BASE
#define FT2_MIXER_LAYOUT_TF_ROTARY_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_ROTARY_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_LINEAR_BASE
#define FT2_MIXER_LAYOUT_TF_LINEAR_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_LINEAR_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_COMBO_BASE
#define FT2_MIXER_LAYOUT_TF_COMBO_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_COMBO_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_METER_BASE
#define FT2_MIXER_LAYOUT_TF_METER_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_METER_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_PARAM_BASE
#define FT2_MIXER_LAYOUT_TF_PARAM_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_PARAM_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_ENV_BASE
#define FT2_MIXER_LAYOUT_TF_ENV_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_ENV_COUNT 0

#ifndef FT2_MIXER_LAYOUT_TF_GROUP_BASE
#define FT2_MIXER_LAYOUT_TF_GROUP_BASE 0
#endif
#define FT2_MIXER_LAYOUT_TF_GROUP_COUNT 0

#ifndef FT2_MIXER_LAYOUT_MIXER_STRIP_BASE
#define FT2_MIXER_LAYOUT_MIXER_STRIP_BASE 0
#endif
#define FT2_MIXER_LAYOUT_MIXER_STRIP_COUNT 16

#ifndef FT2_MIXER_LAYOUT_MIXER_GAIN_BASE
#define FT2_MIXER_LAYOUT_MIXER_GAIN_BASE 0
#endif
#define FT2_MIXER_LAYOUT_MIXER_GAIN_COUNT 16

#ifndef FT2_MIXER_LAYOUT_MIXER_PAN_BASE
#define FT2_MIXER_LAYOUT_MIXER_PAN_BASE 0
#endif
#define FT2_MIXER_LAYOUT_MIXER_PAN_COUNT 16

#ifndef FT2_MIXER_LAYOUT_MIXER_MUTE_BASE
#define FT2_MIXER_LAYOUT_MIXER_MUTE_BASE 0
#endif
#define FT2_MIXER_LAYOUT_MIXER_MUTE_COUNT 16

#ifndef FT2_MIXER_LAYOUT_MIXER_SCOPE_BASE
#define FT2_MIXER_LAYOUT_MIXER_SCOPE_BASE 0
#endif
#define FT2_MIXER_LAYOUT_MIXER_SCOPE_COUNT 16

#ifndef FT2_MIXER_LAYOUT_MIXER_MASTER_BASE
#define FT2_MIXER_LAYOUT_MIXER_MASTER_BASE 0
#endif
#define FT2_MIXER_LAYOUT_MIXER_MASTER_COUNT 1

#ifndef FT2_MIXER_LAYOUT_DSP_WINDOW_BASE
#define FT2_MIXER_LAYOUT_DSP_WINDOW_BASE 0
#endif
#define FT2_MIXER_LAYOUT_DSP_WINDOW_COUNT 0

#ifndef FT2_MIXER_LAYOUT_DSP_SLOT_BASE
#define FT2_MIXER_LAYOUT_DSP_SLOT_BASE 0
#endif
#define FT2_MIXER_LAYOUT_DSP_SLOT_COUNT 4

#ifndef FT2_MIXER_LAYOUT_DSP_MENU_BASE
#define FT2_MIXER_LAYOUT_DSP_MENU_BASE 0
#endif
#define FT2_MIXER_LAYOUT_DSP_MENU_COUNT 1

#ifndef FT2_MIXER_LAYOUT_DSP_PARAM_BASE
#define FT2_MIXER_LAYOUT_DSP_PARAM_BASE 0
#endif
#define FT2_MIXER_LAYOUT_DSP_PARAM_COUNT 8

typedef enum {
    FT2_MIXER_LAYOUT_ACTION_NONE = 0,
    FT2_MIXER_LAYOUT_ACTION_MIXER_EXIT_2_DOWN = 1,
    FT2_MIXER_LAYOUT_ACTION_MIXER_EXIT_2_UP = 2,
    FT2_MIXER_LAYOUT_ACTION_MIX_MASTER_UP_4_DOWN = 3,
    FT2_MIXER_LAYOUT_ACTION_MIX_MASTER_UP_4_UP = 4,
    FT2_MIXER_LAYOUT_ACTION_MIX_MASTER_DN_5_DOWN = 5,
    FT2_MIXER_LAYOUT_ACTION_MIX_MASTER_DN_5_UP = 6,
    FT2_MIXER_LAYOUT_ACTION_MIX_MASTER_FX_6_DOWN = 7,
    FT2_MIXER_LAYOUT_ACTION_MIX_MASTER_FX_6_UP = 8,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_0_12_DOWN = 9,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_0_12_UP = 10,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_0_13_DOWN = 11,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_0_13_UP = 12,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_0_14_DOWN = 13,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_0_14_UP = 14,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_1_20_DOWN = 15,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_1_20_UP = 16,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_1_21_DOWN = 17,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_1_21_UP = 18,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_1_22_DOWN = 19,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_1_22_UP = 20,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_2_28_DOWN = 21,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_2_28_UP = 22,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_2_29_DOWN = 23,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_2_29_UP = 24,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_2_30_DOWN = 25,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_2_30_UP = 26,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_3_36_DOWN = 27,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_3_36_UP = 28,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_3_37_DOWN = 29,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_3_37_UP = 30,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_3_38_DOWN = 31,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_3_38_UP = 32,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_4_44_DOWN = 33,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_4_44_UP = 34,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_4_45_DOWN = 35,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_4_45_UP = 36,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_4_46_DOWN = 37,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_4_46_UP = 38,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_5_52_DOWN = 39,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_5_52_UP = 40,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_5_53_DOWN = 41,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_5_53_UP = 42,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_5_54_DOWN = 43,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_5_54_UP = 44,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_6_60_DOWN = 45,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_6_60_UP = 46,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_6_61_DOWN = 47,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_6_61_UP = 48,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_6_62_DOWN = 49,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_6_62_UP = 50,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_7_68_DOWN = 51,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_7_68_UP = 52,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_7_69_DOWN = 53,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_7_69_UP = 54,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_7_70_DOWN = 55,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_7_70_UP = 56,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_8_76_DOWN = 57,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_8_76_UP = 58,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_8_77_DOWN = 59,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_8_77_UP = 60,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_8_78_DOWN = 61,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_8_78_UP = 62,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_9_84_DOWN = 63,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_9_84_UP = 64,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_9_85_DOWN = 65,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_9_85_UP = 66,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_9_86_DOWN = 67,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_9_86_UP = 68,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_10_92_DOWN = 69,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_10_92_UP = 70,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_10_93_DOWN = 71,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_10_93_UP = 72,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_10_94_DOWN = 73,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_10_94_UP = 74,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_11_100_DOWN = 75,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_11_100_UP = 76,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_11_101_DOWN = 77,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_11_101_UP = 78,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_11_102_DOWN = 79,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_11_102_UP = 80,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_12_108_DOWN = 81,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_12_108_UP = 82,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_12_109_DOWN = 83,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_12_109_UP = 84,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_12_110_DOWN = 85,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_12_110_UP = 86,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_13_116_DOWN = 87,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_13_116_UP = 88,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_13_117_DOWN = 89,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_13_117_UP = 90,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_13_118_DOWN = 91,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_13_118_UP = 92,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_14_124_DOWN = 93,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_14_124_UP = 94,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_14_125_DOWN = 95,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_14_125_UP = 96,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_14_126_DOWN = 97,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_14_126_UP = 98,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_15_132_DOWN = 99,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_UP_15_132_UP = 100,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_15_133_DOWN = 101,
    FT2_MIXER_LAYOUT_ACTION_MIX_GAIN_DN_15_133_UP = 102,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_15_134_DOWN = 103,
    FT2_MIXER_LAYOUT_ACTION_MIX_FX_15_134_UP = 104,
    FT2_MIXER_LAYOUT_ACTION_SCROLLBAR_151_148 = 105,
} ft2_mixer_layout_action_id_t;

extern const ft2_ui_layout_desc_t ft2_mixer_layout_layout;
