set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

if(NOT DEFINED RASPI_TOOLCHAIN_PREFIX)
    set(RASPI_TOOLCHAIN_PREFIX arm-linux-gnueabihf)
endif()

set(CMAKE_C_COMPILER "${RASPI_TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${RASPI_TOOLCHAIN_PREFIX}-g++")

if(DEFINED ENV{RASPI_SYSROOT} AND NOT "$ENV{RASPI_SYSROOT}" STREQUAL "")
    set(CMAKE_SYSROOT "$ENV{RASPI_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH "$ENV{RASPI_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
