set(CMAKE_SYSTEM_NAME Darwin)

if(NOT DEFINED ENV{OSXCROSS_ROOT} OR "$ENV{OSXCROSS_ROOT}" STREQUAL "")
    message(FATAL_ERROR "OSXCROSS_ROOT must point at an osxcross installation")
endif()

if(DEFINED ENV{OSXCROSS_TARGET} AND NOT "$ENV{OSXCROSS_TARGET}" STREQUAL "")
    set(OSXCROSS_TARGET "$ENV{OSXCROSS_TARGET}")
elseif(NOT DEFINED OSXCROSS_TARGET)
    set(OSXCROSS_TARGET o64-clang)
endif()

set(CMAKE_C_COMPILER "$ENV{OSXCROSS_ROOT}/bin/${OSXCROSS_TARGET}")
set(CMAKE_CXX_COMPILER "$ENV{OSXCROSS_ROOT}/bin/${OSXCROSS_TARGET}++")

if(DEFINED ENV{OSXCROSS_SDKROOT} AND NOT "$ENV{OSXCROSS_SDKROOT}" STREQUAL "")
    set(CMAKE_OSX_SYSROOT "$ENV{OSXCROSS_SDKROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH "$ENV{OSXCROSS_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
